# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
#   workflow_run: 
#     workflows: ["Test Build"]
#     types:
#       - completed # Only trigger, when the build workflow succeeded
    

jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build using Node.js ${{ matrix.node-version }} for release ${{ env.RELEASE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run package
    - name: Publishing
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./packages/client-parser.exe"
        token: ${{ secrets.GITHUB_TOKEN }}
